export const THEME_STORAGE_KEY = 'tomato-theme-v2'

export const APP_THEMES = [
  {
    id: 'ember-charcoal',
    name: 'Ember Charcoal',
    mode: 'dark',
    tokens: {
      'app-bg': '#141413',
      'text-primary': '#faf9f5',
      'text-muted': '#d6d2ca',
      'panel-bg': '#252422',
      'panel-soft': '#1d1c1a',
      'border-color': '#3a3935',
      accent: '#d97757',
      'accent-strong': '#c56545',
      'accent-text': '#ffffff',
      'bubble-mine': '#d97757',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#b0aea5',
      'bubble-other-text': '#151412',
      'input-bg': '#2d2c2a',
      'glow-a': 'rgba(217, 119, 87, 0.22)',
      'glow-b': 'rgba(106, 155, 204, 0.2)',
      'glow-c': 'rgba(120, 140, 93, 0.18)',
      'font-heading': 'Poppins, Arial, sans-serif',
      'font-body': 'Lora, Georgia, serif',
    },
  },
  {
    id: 'ivory-forest',
    name: 'Ivory Forest',
    mode: 'light',
    tokens: {
      'app-bg': '#f8f5ec',
      'text-primary': '#1f2b1f',
      'text-muted': '#4f6050',
      'panel-bg': '#ffffff',
      'panel-soft': '#eef3e8',
      'border-color': '#cfd9c8',
      accent: '#3d7a4a',
      'accent-strong': '#2f653b',
      'accent-text': '#ffffff',
      'bubble-mine': '#3d7a4a',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#e8efe1',
      'bubble-other-text': '#1f2b1f',
      'input-bg': '#ffffff',
      'glow-a': 'rgba(61, 122, 74, 0.2)',
      'glow-b': 'rgba(176, 205, 165, 0.24)',
      'glow-c': 'rgba(130, 173, 140, 0.2)',
      'font-heading': 'Playfair Display, Georgia, serif',
      'font-body': 'Nunito Sans, Verdana, sans-serif',
    },
  },
  {
    id: 'ocean-slate',
    name: 'Ocean Slate',
    mode: 'dark',
    tokens: {
      'app-bg': '#121a24',
      'text-primary': '#e8f0f9',
      'text-muted': '#adc3d9',
      'panel-bg': '#1c2633',
      'panel-soft': '#18212d',
      'border-color': '#304357',
      accent: '#4f8fc7',
      'accent-strong': '#3e79ac',
      'accent-text': '#ffffff',
      'bubble-mine': '#4f8fc7',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#2a3a4a',
      'bubble-other-text': '#e8f0f9',
      'input-bg': '#233142',
      'glow-a': 'rgba(79, 143, 199, 0.24)',
      'glow-b': 'rgba(85, 132, 185, 0.2)',
      'glow-c': 'rgba(92, 166, 204, 0.18)',
      'font-heading': 'Montserrat, Arial, sans-serif',
      'font-body': 'Source Sans 3, Tahoma, sans-serif',
    },
  },
  {
    id: 'sand-sunrise',
    name: 'Sand Sunrise',
    mode: 'light',
    tokens: {
      'app-bg': '#fbf3e8',
      'text-primary': '#4b2e1e',
      'text-muted': '#7e5c48',
      'panel-bg': '#fffaf3',
      'panel-soft': '#f2e2cf',
      'border-color': '#e5cbb0',
      accent: '#df8e4f',
      'accent-strong': '#cb7a3d',
      'accent-text': '#ffffff',
      'bubble-mine': '#df8e4f',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#f1dfcb',
      'bubble-other-text': '#4b2e1e',
      'input-bg': '#fff8ef',
      'glow-a': 'rgba(223, 142, 79, 0.24)',
      'glow-b': 'rgba(236, 178, 119, 0.22)',
      'glow-c': 'rgba(198, 149, 106, 0.2)',
      'font-heading': 'Fraunces, Georgia, serif',
      'font-body': 'Manrope, Arial, sans-serif',
    },
  },
  {
    id: 'mint-ledger',
    name: 'Mint Ledger',
    mode: 'light',
    tokens: {
      'app-bg': '#eef7f3',
      'text-primary': '#14322c',
      'text-muted': '#3b5f58',
      'panel-bg': '#f8fffc',
      'panel-soft': '#dceee8',
      'border-color': '#b8d3ca',
      accent: '#2e8f74',
      'accent-strong': '#23735c',
      'accent-text': '#ffffff',
      'bubble-mine': '#2e8f74',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#d8ebe4',
      'bubble-other-text': '#14322c',
      'input-bg': '#ffffff',
      'glow-a': 'rgba(46, 143, 116, 0.2)',
      'glow-b': 'rgba(72, 158, 130, 0.2)',
      'glow-c': 'rgba(128, 189, 170, 0.2)',
      'font-heading': 'Rubik, Arial, sans-serif',
      'font-body': 'Noto Sans, Helvetica, sans-serif',
    },
  },
  {
    id: 'ruby-night',
    name: 'Ruby Night',
    mode: 'dark',
    tokens: {
      'app-bg': '#1a1114',
      'text-primary': '#f7e9ef',
      'text-muted': '#d3b6c2',
      'panel-bg': '#25171c',
      'panel-soft': '#201419',
      'border-color': '#4d313b',
      accent: '#c45b7a',
      'accent-strong': '#a94764',
      'accent-text': '#ffffff',
      'bubble-mine': '#c45b7a',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#3c252f',
      'bubble-other-text': '#f7e9ef',
      'input-bg': '#2d1c23',
      'glow-a': 'rgba(196, 91, 122, 0.24)',
      'glow-b': 'rgba(171, 84, 125, 0.2)',
      'glow-c': 'rgba(112, 61, 84, 0.2)',
      'font-heading': 'Cormorant Garamond, Georgia, serif',
      'font-body': 'Cabin, Arial, sans-serif',
    },
  },
  {
    id: 'aurora-teal',
    name: 'Aurora Teal',
    mode: 'dark',
    tokens: {
      'app-bg': '#0f1f22',
      'text-primary': '#e7f6f8',
      'text-muted': '#b0d4d8',
      'panel-bg': '#173036',
      'panel-soft': '#12282d',
      'border-color': '#2d5058',
      accent: '#4eb3c5',
      'accent-strong': '#3798aa',
      'accent-text': '#ffffff',
      'bubble-mine': '#4eb3c5',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#244850',
      'bubble-other-text': '#e7f6f8',
      'input-bg': '#1e3d44',
      'glow-a': 'rgba(78, 179, 197, 0.24)',
      'glow-b': 'rgba(61, 147, 172, 0.2)',
      'glow-c': 'rgba(58, 114, 126, 0.2)',
      'font-heading': 'Space Grotesk, Arial, sans-serif',
      'font-body': 'Work Sans, Helvetica, sans-serif',
    },
  },
  {
    id: 'copper-paper',
    name: 'Copper Paper',
    mode: 'light',
    tokens: {
      'app-bg': '#f8eee3',
      'text-primary': '#3b2415',
      'text-muted': '#725140',
      'panel-bg': '#fff8f0',
      'panel-soft': '#ecd8c5',
      'border-color': '#d9ba9e',
      accent: '#b46a3e',
      'accent-strong': '#9d5530',
      'accent-text': '#ffffff',
      'bubble-mine': '#b46a3e',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#edd8c5',
      'bubble-other-text': '#3b2415',
      'input-bg': '#fff9f3',
      'glow-a': 'rgba(180, 106, 62, 0.24)',
      'glow-b': 'rgba(198, 132, 89, 0.2)',
      'glow-c': 'rgba(168, 119, 87, 0.2)',
      'font-heading': 'Libre Baskerville, Georgia, serif',
      'font-body': 'PT Sans, Arial, sans-serif',
    },
  },
  {
    id: 'graphite-neon',
    name: 'Graphite Neon',
    mode: 'dark',
    tokens: {
      'app-bg': '#111216',
      'text-primary': '#f1f5ff',
      'text-muted': '#bcc6dd',
      'panel-bg': '#1c1f28',
      'panel-soft': '#161922',
      'border-color': '#343b4e',
      accent: '#5b86ff',
      'accent-strong': '#3f6de8',
      'accent-text': '#ffffff',
      'bubble-mine': '#5b86ff',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#2a3040',
      'bubble-other-text': '#f1f5ff',
      'input-bg': '#222737',
      'glow-a': 'rgba(91, 134, 255, 0.24)',
      'glow-b': 'rgba(111, 161, 255, 0.2)',
      'glow-c': 'rgba(61, 95, 180, 0.2)',
      'font-heading': 'Oswald, Arial, sans-serif',
      'font-body': 'Assistant, Helvetica, sans-serif',
    },
  },
  {
    id: 'plum-ink',
    name: 'Plum Ink',
    mode: 'dark',
    tokens: {
      'app-bg': '#1a1520',
      'text-primary': '#f4ebff',
      'text-muted': '#ccb9df',
      'panel-bg': '#251d30',
      'panel-soft': '#1f1929',
      'border-color': '#46365b',
      accent: '#9a6fd1',
      'accent-strong': '#8357bd',
      'accent-text': '#ffffff',
      'bubble-mine': '#9a6fd1',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#382b49',
      'bubble-other-text': '#f4ebff',
      'input-bg': '#2d233c',
      'glow-a': 'rgba(154, 111, 209, 0.24)',
      'glow-b': 'rgba(129, 93, 185, 0.2)',
      'glow-c': 'rgba(103, 78, 150, 0.2)',
      'font-heading': 'IBM Plex Serif, Georgia, serif',
      'font-body': 'IBM Plex Sans, Arial, sans-serif',
    },
  },
  {
    id: 'cobalt-snow',
    name: 'Cobalt Snow',
    mode: 'light',
    tokens: {
      'app-bg': '#eef4fb',
      'text-primary': '#162f4f',
      'text-muted': '#47668b',
      'panel-bg': '#f7fbff',
      'panel-soft': '#dce9f7',
      'border-color': '#b9cde6',
      accent: '#3e74b5',
      'accent-strong': '#2e5f9c',
      'accent-text': '#ffffff',
      'bubble-mine': '#3e74b5',
      'bubble-mine-text': '#ffffff',
      'bubble-other': '#d7e6f7',
      'bubble-other-text': '#162f4f',
      'input-bg': '#ffffff',
      'glow-a': 'rgba(62, 116, 181, 0.22)',
      'glow-b': 'rgba(118, 161, 212, 0.2)',
      'glow-c': 'rgba(76, 132, 191, 0.2)',
      'font-heading': 'Merriweather, Georgia, serif',
      'font-body': 'DM Sans, Arial, sans-serif',
    },
  },
]

export const DEFAULT_THEME_ID = APP_THEMES[0].id
